name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with a custom token
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT }}
          persist-credentials: true
      
      # Configure git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      # Run the blog post workflow
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.virtualizationhowto.com/feed/"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          gh_token: ${{ secrets.PAT }}
